### ISSUE TITLE
Can you specify what get variables to not show?

### ISSUE THREAD

**Issue by ghost** [stefangabos/Zebra_Pagination#15]
Reading your documentation, when creating the links in the pagination it will take all variables found in $_GET and add it to the base URL. My question is, is there a way to tell your script to exclude certain $_GET variables? So if I have this url:

`mysite.com/search.php?source=header&page=1`

Is there a way when it generates the pagination link, is there a way I can say to exclude source? So then the link the pagination script uses would then be:

`mysite.com/search.php?page=1`

I just have some hidden get variables via htaccess that I dont want displayed on the page.

**Comment by ghost** [comment]
I just went ahead and added code to do this. Now all I have to do is:

`$pagination->exclude_query('name1,name2');`

And it will exclude those from the overall query...

**Comment by stefangabos** [comment]
use the 'base_url' method. see https://stefangabos.github.io/Zebra_Pagination/Zebra_Pagination/Zebra_Pagination.html#methodbase_url

**Comment by ghost** [comment]
> 
> 
> use the 'base_url' method. see https://stefangabos.github.io/Zebra_Pagination/Zebra_Pagination/Zebra_Pagination.html#methodbase_url

Sorry for late response, yes using base_url would had also resolved my issue. Thanks for the heads up!
