### ISSUE TITLE
Pagination does not display if record is only "one page long"

### ISSUE THREAD

**Issue by meshachviktor** [stefangabos/Zebra_Pagination#16]
I dont know if zebra pagination was designed that way or if it is an error in my code but the pagination links refuse to show when the data to be displayed can be contained in one page i.e. when the data is  not up to two pages in length. for the projec it takes nine data per page max but when the result is nine or less the pagination links dont show

**Comment by stefangabos** [comment]
See [documentation](https://stefangabos.github.io/Zebra_Pagination/Zebra_Pagination/Zebra_Pagination.html#methodalways_show_navigation)

**Comment by stefangabos** [comment]
...that seems to be set to `true` by default so I'll have a look at it

**Comment by stefangabos** [comment]
should be fixed now, download again, test, and let me know if it works. thanks!

**Comment by meshachviktor** [comment]
Oh yes! It is displaying now. Thanks for the quick fix!
