### ISSUE TITLE
MySql Example not working

### ISSUE THREAD

**Issue by ghost** [stefangabos/Zebra_Pagination#17]
Hello the mysql example you gave does not work, the query fails.

**Comment by stefangabos** [comment]
it works for me. what errors do yo see?

**Comment by stefangabos** [comment]
oh, you mean the example from the GitHub readme...i am fixing it now

**Comment by stefangabos** [comment]
it's fixed now

**Comment by ghost** [comment]
getpage() mysql gives an error saying its an undefined property.

**Comment by stefangabos** [comment]
then it's not my example. i just tried the example from the examples folder, as well as the one from the readme and both are working

**Comment by ghost** [comment]
> then it's not my example. i just tried the example from the examples folder, as well as the one from the readme and both are working

I am trying for mysqli, but it gives an error saying that its an undefined property i have followed all the steps you have showed.

// My query:
("SELECT natural, chp_nme
         FROM 
         clothe
         LIMIT  . (($pagination->get_page() - 1) * $records_per_page) . ', ' . $records_per_page . '");;;

//Error
 Undefined property: Zebra_Pagination::$get_page

**Comment by stefangabos** [comment]
The error is not in the code you showed me here.
The error says that you are somewhere using `get_page` as a `property` instead of a `method`.
This means that you forgot to use parenthesis somewhere and that you are using `$pagination->get_page` instead of `$pagination->get_page()`
