### ISSUE TITLE
Use div in page

### ISSUE THREAD

**Issue by volkankoc** [stefangabos/Zebra_Pagination#19]
I want to use div. But it shows up side by side, not side by side. Can you help me
Ex.
<div class="row">
<div class="col">data</div>
</div>
result
data
data
data

but I want it to be this way data data data

**Comment by stefangabos** [comment]
please send me a screenshot or something because i don't understand what you need

**Comment by volkankoc** [comment]
![question](https://user-images.githubusercontent.com/22777823/81468359-c366f980-91e7-11ea-839c-18363b6294aa.png)
I want to edit the content side by side
data-data-data

-----
This is what happens when I use div

**Comment by stefangabos** [comment]
i don't understand what does that have to do with the pagination class, but other than that just using 
```html
<div style="float:left">data</div>
```
would float your divs left...
