### ISSUE TITLE
Cannot apply custom template 

### ISSUE THREAD

**Issue by Bilge** [stefangabos/Zebra_Pagination#22]
Since all the templated markup is hard-coded in a giant string concatenation, it is not very easy to modify. For example, if I want to add `rel="nofollow"` to the pagination links, there isn't a clear extension point to do this.

If the DOM was instead constructed using an object, such as [DOM crawler](https://symfony.com/doc/current/components/dom_crawler.html), that object could be exposed to users to easily modify any aspect of the output in an object-oriented way prior to output.

**Comment by stefangabos** [comment]
use the `render` method with the `true` argument and post-process the output

**Comment by stefangabos** [comment]
i could actually make something like running a callback function (if defined by the user) before generating each pagination link but i feel that is something way out of proportions for such a simple pagination script.
any thoughts?

**Comment by stefangabos** [comment]
also, i am grateful for all your constructive feedback on the other issues mentioned
