### ISSUE TITLE
Breaks on numeric path components

### ISSUE THREAD

**Issue by Bilge** [stefangabos/Zebra_Pagination#25]
Given that I want my page ID to be a path component, I set `variable_name` to the empty string (`''`) and `method` to `url`. This works when all other path components are non-numeric, e.g. `foo.com/bar`. In this case, the library will append the page number, e.g. `foo.com/bar/1`. However, if there are other numeric path components, the library gets confused and thinks it's the page number. e.g. `foo.com/123` will treat `123` as the page number even if it is not. That is, navigating to page 1 will redirect to `foo.com/1` instead of `foo.com/123/1`.

**Comment by stefangabos** [comment]
This can be fixed only if we assume that the page number is the last segment in the URL, I guess
Which is still better than nothing.
On it

**Comment by stefangabos** [comment]
having an empty `variable_name` requires `base_url` to be explicitly set in this case
