### ISSUE TITLE
Any Alternative to LIMITs

### ISSUE THREAD

**Issue by kezenwa** [stefangabos/Zebra_Pagination#32]
Hello

AM aware this script isn't tied to any specific database type e.g MYSQL but am looking for an alternative to the widely used way of Pagination called LIMITs which becomes an issue with very large datasets

**Comment by stefangabos** [comment]
since this isn't tied to a database, it's up to you on how you use the values returned by the library. certainly, you can use something other than LIMIT (like OFFSET, for example)
