### ISSUE TITLE
Ampersands in URL parameters incorrectly handled

### ISSUE THREAD

**Issue by Tom-Lovatt** [stefangabos/Zebra_Pagination#34]
Steps to reproduce:

1. Add a URL parameter with a (correctly-encoded) ampersand to page 1 E.g /songs/?genre=Rock%26Roll
2. Navigate to page 2

Expected behaviour:
The URL is now /songs/?genre=Rock%26Roll&page=2
Which will be parsed as genre=Rock&Roll, page=2

Actual behaviour:
The URL is now /users/?genre=Rock&Roll&page=2
Which will be parsed as genre=Rock, Roll=<empty>, page=2

It looks like it's caused by the call to urldecode() in Zebra_Pagination.php:903, but I'm not sure what side-effects removing that would cause.

**Comment by stefangabos** [comment]
Thank you for reporting this
I made a fix. I'd really appreciate it if you could validate that it works
Thanks!

**Comment by Tom-Lovatt** [comment]
That fixes it, thanks!

**Comment by stefangabos** [comment]
Thanks for testing it!
I published a new version with this fix included.
Thanks again for reporting and for the feedback!
