### ISSUE TITLE
Wrong link in page "1" button

### ISSUE THREAD

**Issue by rcorsari** [stefangabos/Zebra_Pagination#35]
Weird
I've implemented the library but I do notice a weird "issue"

kindly see this screenshot
https://ibb.co/XLqTDf6

If I click the arrows forth and back OR i click any number, the link under button of page "1" then becomes the current page link

E.G. displaying page 1 as in the screenshot
if I click on any page, e.g. page 4, it then becomes active the button "4" and button "1" become clickable , but if I hover the mouse on button "1" it has the link to page 4
same if from page 1 I click the next button, it goes to page "2" and if I hover on button "1" it is now link to page 2
if I click again the next button, it goes to page "3" and if I hover on button "1" it is now link to page 3

see here
https://ibb.co/sFW35zJ

If I hover on ANY other page button, the link is correct and links to the corresponding page number, only button "1" is the problem

Additional info: I have clicked page "8". Then I begun to click on "<<", at every click the button "1" assumes the value of the current page so.. 
1th click , I'm on page "7" and button "1" links to 7 WHILE button "<<" link correctly to "6"
2nd click ,  I'm on page "6" and button "1" links to 6 WHILE button "<<" link correctly to "5" and so on
when it comes page "2" EITHER button "1" and button "<<" are linking to page "2" and so, via buttons I cannot go back to page "1" :
the unique solution is to manually edit the URL in the browser

Can you hint for some mistake? Or is this a bug?

Thank you

**Comment by stefangabos** [comment]
I am unable to reproduce this.
I tried with the examples in the example folder and they seem to work fine. 
Are you sure you are not always setting ` base_url` to whatever page you are on?

**Comment by rcorsari** [comment]
Hello Stefan thank you for replying

Given the example and given my short page/script too, a new instance of Zebra_Pagination() is made whenever/each time you click a pagination link, since the page is reloaded and so the code is re-run, right?

I don't have any base_url in my code, I have searched the whole directory with Visual Studio Code and the unique occurrences of base_url are all in the Zebra_Pagination.php file
you can see my files here https://github.com/rcorsari/test

Do you have any kind further hint?

**Comment by stefangabos** [comment]
Are you using the latest version?

**Comment by rcorsari** [comment]
Yes latest
you can see my files here
https://github.com/rcorsari/test

**Comment by stefangabos** [comment]
everything seems to be ok with the code so the only thing i can think of is maybe something to do with how your virtual host is setup of something. it's really weird...

**Comment by rcorsari** [comment]
I'll try on a xampp on my desktop
This is a good point , infact I recall that on the development machine I think I had not this issue.
Though, it is also weird that next/previous buttons and also other pages work
Things looks focused on page "1" button's link

How is it "generated"? Also... Since the button label is correctly "1" , in the case I cannot fix the host issue (it is a Synology NAS pretty updated, and I have enabled PHP 7.4.x with apache 2.4.x)
... when label is "1" rather I'd make a code that uses the "1" from the label

unless you don't have some .htaccess tweak to suggest

**Comment by stefangabos** [comment]
no tweak for .htaccess should be necessary when using it like `?page=x`
i'll investigate some more

**Comment by stefangabos** [comment]
you can look in the code starting at line `976` and more specifically, the problem seems to be in the `_build_uri` method at line `979`, when `$i` is `1`

**Comment by stefangabos** [comment]
actually, it's a bit further down if you have more pages, starting at `1006` and the call to `_build_uri` at `1009`, when value is `1`

**Comment by rcorsari** [comment]
Ok
Thank you so much for the availability

One question regarding the class itself

I have done an experiment

I have manually added parameters after the ?page=x
So like ?page=3&foo=abc&Baz=cde
and verified that clicking on another page link e.g. 5 
my query parameters are kept untouched
 ?page=5&foo=abc&Baz=cde

it is coded in the class to retain the others parameters? (just for confirmation) thank you

**Comment by stefangabos** [comment]
yes, your query parameters (other than `page`) remain untouched

**Comment by stefangabos** [comment]
unless you set `preserve_query_string` to `false`

**Comment by rcorsari** [comment]
( sorry slightly off topic: how to "print"/add the query string to the URL? I'm trying to learn these techniques for sorting/filtering purposes, if you have any kind link, thank you)

**Comment by rcorsari** [comment]
P.S. about the original issue of this thread:
if you have any script you want me to run for testing the host behavior, please share it, I'll upload and run it.

**Comment by rcorsari** [comment]
Good morning
I have tried in this moment the code I have shared above on an xampp localhost

same issue, as soon I have clicked page 3 button, the link on button "1" has become a link to page 3

Both on the NAS and in this xampp localhost, I had setup a corresponding virtual host
Now I try without the virtual host

**Comment by rcorsari** [comment]
An additional test
I have set the records per page to as low as 3 per page
so pagination links have become so many
Button to page "1" is permanently shown with second button being the "..." three periods "more" placeholder

total pages are 26 in my case

So I started from page 26 and pressed repeatedly the previous button

It passed correctly page by page down to page "2" ... anyway button "1" is permanently a link to current displayed page, see here

https://ibb.co/hcn1xDz (hover)

( _P.S. if I count the buttons between the two "..." placeholders, I count 9 pages clickable buttons , is there a setting to make those buttons instead of 9, just 5?_ )

Also, clicking the link right before the "..." as example in the screenshot the button "12", the new page now shows button "08" as first button after "..."
and its link is anyway correct, it links to page "8" and current shown page is page "12" and ... 

you may bet on it ... since current page is "12" , button "1" links to page 12

**Comment by rcorsari** [comment]
And final verification tells the issue:

I have removed the Apache virtual host, as written above both in the NAS and in this xampp localhost, are enabled the Apache virtual hosts. Apache in both cases is 2.4.

With virtual host removed , Now I moved the app directory inside the /htdocs one

**without vhost** running the app **now pagination works** as expected

so now I run http://localhost/calls and button "1" always show a link to "http://localhost/calls" (it is not shown the ?page=1 I think because of the SEO setting for avoiding the content duplication)

My vhost is the most basic as possible (I can control  only the xampp one, since in the NAS it is managed from the NAS dashboard automatically with built-in methods, I can only enter the vhost name and the app path)

```
<VirtualHost *:80>
    
    DocumentRoot "C:\calls"
    ServerName calls.localhost

    <Directory "C:\calls">
        Require all granted
        AllowOverride All
    </Directory>

</VirtualHost>
```

as usual my /system32/drivers/etc/hosts is

127.0.0.1     localhost  calls.localhost

**Comment by stefangabos** [comment]
yes, i thought it had to do about the virtual host. i am now trying to test with that
see the [docs](https://stefangabos.github.io/Zebra_Pagination/Zebra_Pagination/Zebra_Pagination.html) regarding the options you can set

**Comment by stefangabos** [comment]
yes, an option called [avoid_duplicate_content](https://stefangabos.github.io/Zebra_Pagination/Zebra_Pagination/Zebra_Pagination.html#methodavoid_duplicate_content) handles that

**Comment by stefangabos** [comment]
ok, i am able to reproduce it now and i am working on it

**Comment by stefangabos** [comment]
Please download now again from https://github.com/stefangabos/Zebra_Pagination/archive/refs/heads/master.zip
Should work now

**Comment by stefangabos** [comment]
The issue was that because you were running the script on the root of the server, the first page's link was calculated as `nothing` / `an empty string` so the first page's `href` was `""`. For browsers this means "the current page's URL".
Now the `href` in these situations is `/`
Thank you for all your feedback

**Comment by rcorsari** [comment]
The vhost is made exactly to allow to place the app directory where you need, we know, and then the Apache server will serve that directory

I need the vhost :-) 

Ok now I try the update

**Comment by stefangabos** [comment]
it should work now regardless of your setup

**Comment by rcorsari** [comment]
Yes I confirm, now it works on the NAS too :-) (P.S. just to know which are the code lines you changed?)

**Comment by stefangabos** [comment]
I am sorry I don't have the time to help you with that. 
Please don't take this the wrong way - I fix any bug reported for my libraries but don't have the time nor the willingness to teach people about PHP/HTML/CSS/JS. 
I am sure that searching YouTube or StackOverflow or simply googling whatever you are looking for will get you on the right path

**Comment by rcorsari** [comment]
:-) ok, you have been pretty kind for all the support and the update, thank you. please for the curiosity , which are the lines involved in the update?

**Comment by stefangabos** [comment]
[Here](https://github.com/stefangabos/Zebra_Pagination/commit/a0fd101719b7ad36e4e993346403079af91b2220#diff-ce36a38f277ca7b0f5e079784123340797f963a5260f52a2a8416fd4bc7e8c49)'s what changed

**Comment by stefangabos** [comment]
I am glad we could get it working for you.
Thank you for reporting the issue and for providing feedback!
Good luck with your project!
