### ISSUE TITLE
Zebra Pagination is not compatible with MySQL 5.5 and later

### ISSUE THREAD

**Issue by saymon9** [stefangabos/Zebra_Pagination#37]
The function `mysql_fetch_assoc` was marked as deprecated starting from PHP 5.5.0 and subsequently removed entirely in PHP 7.0.0. This can lead to compatibility issues and cause the library to crash if you attempt to upgrade to these MySQL versions.

**Comment by stefangabos** [comment]
Zebra_Pagination doesn't use MySQL. It is just a generic library for paginating data. It doesn't know nor care about how you get your data. 
Also, I have no reference to `mysql_fetch_assoc` in my examples.

**Comment by saymon9** [comment]
Thanks @stefangabos for the fast answer and the great library!!. The documentation does a reference to "`mysqli_fetch_assoc`" in the "How to use" section when it explains the usage with "Paginate data from MySQL:"

**Comment by stefangabos** [comment]
That is true. 
But `mysqli_fetch_assoc` is a PHP function that is **not** deprecated (as opposed to the one you first mentioned and which is the old, PHP 4, `mysql_fetch_assoc`). Nor has anything to do with the MySQL version.
