### ISSUE TITLE
Consider marking `_build_uri()` with protected access

### ISSUE THREAD

**Issue by Bilge** [stefangabos/Zebra_Pagination#38]
I had to [fork](https://github.com/Bilge/Zebra_Pagination) this library to [override `_build_uri()`](https://github.com/Bilge/Zebra_Pagination/blob/10394dab573fb5244286b17d557f2598c0a218bd/Zebra_Pagination.php#L769) for my application. In my app, I override this method to provide tight integration with Symfony, by constructing the pagination URLs automatically using the `RouterInterface` and `RequestStack` to detect the current route and generate the paginated URL by passing through any request attributes with the page ID replaced by the one passed to the method.

It works very well, and as far as I can tell, there is no cleaner way to do this using the public interface. However, it would be nice to return to mainline instead of relying on a fork, which is only possible if the accessibility is modified.

**Comment by stefangabos** [comment]
done

**Comment by Bilge** [comment]
I'm not sure if it's necessary (or a good idea) to change the visibility of `$_properties`. I know I did that in my fork, but that was just because I didn't care about breaking encapsulation since I can fully control my environment. For your project, I think it is probably a bad idea to do this (and I certainly don't need it for my use case; in fact I only need the one method I already mentioned).

**Comment by stefangabos** [comment]
You are right - `_properties` should remain private. As for the methods there's no harm in having them as `protected` because if one has to override `_build_uri` then you could as well want to override the other ones related to generating the output
