### ISSUE TITLE
Change to pdo or mysqli

### ISSUE THREAD

**Issue by funkyfela** [stefangabos/Zebra_Pagination#4]
Hello, 

wouldnt be great if you can make the script in pdo or mysqli version since mysql is deprecated?

cheers

**Comment by funkyfela** [comment]
hello. i tried to use it with a search result but working. showing just blank.

$MySQL = '
            SELECT
                SQL_CALC_FOUND_ROWS
                *
            FROM
                ca_processed WHERE date_processed BETWEEN ' . $from . ' AND ' . $to . '
            ORDER BY
                date_processed
            LIMIT
                ' . (($pagination->get_page() - 1) \* $records_per_page) . ', ' . $records_per_page . '
        ';
what could be the cause?

thanks

**Comment by stefangabos** [comment]
Zebra_Pagination doesn't run queries so there's nothing to update on that matter.
That is just an example of how to use the library with MySQL. You could use it with mysqi or PDO but you are the one who runs the queries - my library only helps you create the pagination links
