### ISSUE TITLE
Records don't show when setting page manually or after page count changed

### ISSUE THREAD

**Issue by BillyGeat** [stefangabos/Zebra_Pagination#5]
The class works good but I found a thing that might be a bug.

An example scenario:
I have a page where I can choose witch records should be shown by a drop down box.
First, I have nothing selected, means show all records. Works correctly, I can navigate with the pagination class, total 3 pages.
I enter the 3rd page.
Now, I change the select box to show a category, where only 2 pages are available.
The class correctly shows only 2 pages and marks / selects the last one (nr. 2) but nothing is showing!
In the URL, the ?page parameter still shows ?page=3 - it should show / be ?page=2.

The same thing happens when I set the page manually with set_page(2) for example. The navigation / pagination is correctly selected but the URL has again ?page=3 witch has no records.

**Comment by stefangabos** [comment]
That's logical and expected. As you change the number of records to be shown per page, page 3 becomes a page that will show no records and it's up to you to decide how to handle that. The way I do it is that whenever the user changes the number of records to be shown per page, I direct them to the first page
