### ISSUE TITLE
Update to mysqli and fix paginate data from MySQL in reverse order

### ISSUE THREAD

**Issue by elraghifary** [stefangabos/Zebra_Pagination#6]
Hi, I can't create a PR.

I update how to use paginate data from MySQL into mysqli version, here's the gist:
[Paginate data from MySQL](https://gist.github.com/elraghifary/4068f2f502a07e5117f21c4941f0663f)

Also, I update how to use paginate data from MySQL in reverse order, here's the gist:
[Paginate data from MySQL in reverse order](https://gist.github.com/elraghifary/6fc976398ee01ba9332d7b87c1375b3f)

Thank you for awesome library.

**Comment by stefangabos** [comment]
This is now implemented. Thank you!
