### ISSUE TITLE
How to hide zero on the left side

### ISSUE THREAD

**Issue by Mianovag** [stefangabos/Zebra_Pagination#8]
owesome script, so fat it works but when you have pages over three number (001  ....   101) the million dolar question is what should i do to display this way (1 .... 101)

**Comment by stefangabos** [comment]
That's an easy way to make a million dollar then because the answer is in the [documentation](https://stefangabos.github.io/Zebra_Pagination/Zebra_Pagination/Zebra_Pagination.html#methodpadding)
